### ISSUE TITLE
Can't install as a dependency via stack/hackage

### ISSUE THREAD

**Issue by ch3pjw** [thoughtbot/persistent-database-url#9]
I just tried to install this via adding it as an `extra-dep` in my stack config with `lts-9.6` as my resolver, and I got
```
In the dependencies for persistent-database-url-1.1.0:
    uri-bytestring-0.2.3.3 must match <0.2.0 (latest applicable is 0.1.9.2)
needed due to <my project> -> persistent-database-url-1.1
```
I can `stack build` `uri-bytestring` fine from a fresh clone and the tests pass, so I think the constraint on hackage is too restrictive?

I've worked around it with the following in my `stack.yaml` to install it from a clone rather than hackage:
```yaml
packages:
  - location:
      git: git@github.com:thoughtbot/persistent-database-url.git
      commit: 09782a464f4c50f91b78e118ae56010636cd38cd
    extra-dep: true
```
but I'd rather use an official release.

**Comment by venteto** [comment]
I'm getting a similar error over a year later and wonder if it needs to be bumped again?
Is there any chance this might be added to Stackage/LTS Haskell?

**Comment by tuomohopia** [comment]
With a later version of Stack the above solution does not work anymore. You can solve it by adding an entry to `extra-deps` in `stack.yaml`:

```yaml
extra-deps:
- github: thoughtbot/persistent-database-url
  commit: 0cdaf99d91592b22a261eecb29820b29679e929b
```
